# NO INDEX | NOT NULL
--source noindex.inc
--source notnull.inc
--source string.inc

# NO INDEX | NULLABLE
--source noindex.inc
--source nullable.inc
--source nullable_string.inc
--source string.inc

# INDEXED  | NOT NULL
--source index.inc
--source notnull.inc
--source string.inc

# INDEXED  | NULLABLE
--source index.inc
--source nullable.inc
--source nullable_string.inc
--source string.inc

# NO INDEX | NOT NULL
--source noindex.inc
--source notnull.inc
--source string.inc

# NO INDEX | NULLABLE
--source noindex.inc
--source nullable.inc
--source nullable_string.inc
--source string.inc

# INDEXED  | NOT NULL
--source index.inc
--source notnull.inc
--source string.inc

# INDEXED  | NULLABLE
--source index.inc
--source nullable.inc
--source nullable_string.inc
--source string.inc
