# NO INDEX | NOT NULL
--source noindex.inc
--source notnull.inc
--source temporal.inc

# NO INDEX | NULLABLE
--source noindex.inc
--source nullable.inc
--source nullable_temporal.inc
--source temporal.inc

# INDEXED  | NOT NULL
--source index.inc
--source notnull.inc
--source temporal.inc

# INDEXED  | NULLABLE
--source index.inc
--source nullable.inc
--source nullable_temporal.inc
--source temporal.inc

# NO INDEX | NOT NULL
--source noindex.inc
--source notnull.inc
--source temporal.inc

# NO INDEX | NULLABLE
--source noindex.inc
--source nullable.inc
--source nullable_temporal.inc
--source temporal.inc

# INDEXED  | NOT NULL
--source index.inc
--source notnull.inc
--source temporal.inc

# INDEXED  | NULLABLE
--source index.inc
--source nullable.inc
--source nullable_temporal.inc
--source temporal.inc
