/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef hbase_engine_CONSTANTS_H
#define hbase_engine_CONSTANTS_H

#include "hbase_engine_types.h"

namespace com { namespace nearinfinity { namespace hbase_engine {

class hbase_engineConstants {
 public:
  hbase_engineConstants();

};

extern const hbase_engineConstants g_hbase_engine_constants;

}}} // namespace

#endif
