/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "hbase_engine_constants.h"

namespace com { namespace nearinfinity { namespace hbase_engine {

const hbase_engineConstants g_hbase_engine_constants;

hbase_engineConstants::hbase_engineConstants() {
}

}}} // namespace

