/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef hbase_engine_TYPES_H
#define hbase_engine_TYPES_H

#include <Thrift.h>
#include <TApplicationException.h>
#include <protocol/TProtocol.h>
#include <transport/TTransport.h>



namespace com { namespace nearinfinity { namespace hbase_engine {

struct hbase_engine_types {
  enum type {
    CLOUD = 1
  };
};

extern const std::map<int, const char*> _hbase_engine_types_VALUES_TO_NAMES;

}}} // namespace

#endif
