/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "hbase_engine_types.h"

namespace com { namespace nearinfinity { namespace hbase_engine {

int _khbase_engine_typesValues[] = {
  hbase_engine_types::CLOUD
};
const char* _khbase_engine_typesNames[] = {
  "CLOUD"
};
const std::map<int, const char*> _hbase_engine_types_VALUES_TO_NAMES(::apache::thrift::TEnumIterator(1, _khbase_engine_typesValues, _khbase_engine_typesNames), ::apache::thrift::TEnumIterator(-1, NULL, NULL));

}}} // namespace
