require 'active_record'
require 'yaml'

task :default => :migrate

desc "Migrate the database through scripts in db/migrate. Target specific version with VERSION=x"
task :migrate => :environment do
  puts "Dropping tables in database"
  tables = ActiveRecord::Base.connection.execute("show tables like '%'").to_a
  ActiveRecord::Base.connection.execute("drop table #{tables.join(',')}") unless tables.empty?
  puts "Migrating schema"
  ActiveRecord::Migrator.migrate('db/migrate', ENV["VERSION"] ? ENV["VERSION"].to_i : nil )
end

task :environment do
  ActiveRecord::Base.establish_connection(YAML::load(File.open('database.yml')))
end
