/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.nearinfinity.honeycomb.mysql;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public interface mysql {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"mysql\",\"namespace\":\"com.nearinfinity.honeycomb.mysql\",\"types\":[{\"type\":\"fixed\",\"name\":\"Position\",\"size\":16},{\"type\":\"record\",\"name\":\"Row\",\"fields\":[{\"name\":\"records\",\"type\":{\"type\":\"map\",\"values\":\"bytes\",\"avro.java.string\":\"String\"}}]}],\"messages\":{}}");

  @SuppressWarnings("all")
  public interface Callback extends mysql {
    public static final org.apache.avro.Protocol PROTOCOL = com.nearinfinity.honeycomb.mysql.mysql.PROTOCOL;
  }
}