/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.nearinfinity.honeycomb.mysql;  
@SuppressWarnings("all")
@org.apache.avro.specific.FixedSize(16)
@org.apache.avro.specific.AvroGenerated
public class Position extends org.apache.avro.specific.SpecificFixed {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"fixed\",\"name\":\"Position\",\"namespace\":\"com.nearinfinity.honeycomb.mysql\",\"size\":16}");
  
  /** Creates a new Position */
  public Position() {
    super();
  }
  
  /** Creates a new Position with the given bytes */
  public Position(byte[] bytes) {
    super(bytes);
  }
}
